package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.21 13:54:59 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KayttajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi41 */
  @Test
  public void testRekisteroi41() {    // Kayttaja: 41
    Kayttaja aku1 = new Kayttaja(); 
    assertEquals("From: Kayttaja line: 43", 0, aku1.getKid()); 
    aku1.rekisteroi(); 
    Kayttaja aku2 = new Kayttaja(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getKid(); 
    int n2 = aku2.getKid(); 
    assertEquals("From: Kayttaja line: 49", n2-1, n1); 
    assertEquals("From: Kayttaja line: 50", n1+1, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKid63 */
  @Test
  public void testGetKid63() {    // Kayttaja: 63
    Kayttaja aku1 = new Kayttaja(); 
    assertEquals("From: Kayttaja line: 65", 0, aku1.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse118 */
  @Test
  public void testParse118() {    // Kayttaja: 118
    Kayttaja kayttaja = new Kayttaja(); 
    kayttaja.parse("   3   | Aada     | 35   "); 
    assertEquals("From: Kayttaja line: 121", 3, kayttaja.getKid()); 
    assertEquals("From: Kayttaja line: 122", true, kayttaja.toString().startsWith("3|Aada|35")); 
    kayttaja.rekisteroi(); 
    int n = kayttaja.getKid(); 
    kayttaja.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kayttaja.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kayttaja line: 128", n+20+1, kayttaja.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString143 */
  @Test
  public void testToString143() {    // Kayttaja: 143
    Kayttaja aada = new Kayttaja(); 
    assertEquals("From: Kayttaja line: 145", "0||0", aada.toString()); 
  } // Generated by ComTest END
}