package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.21 10:28:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa39 */
  @Test
  public void testLisaa39() {    // Kayttajat: 39
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja aada = new Kayttaja(), ben = new Kayttaja(); 
    assertEquals("From: Kayttajat line: 42", 0, kayttajat.getLkm()); 
    kayttajat.lisaa(aada); assertEquals("From: Kayttajat line: 43", 1, kayttajat.getLkm()); 
    kayttajat.lisaa(ben); assertEquals("From: Kayttajat line: 44", 2, kayttajat.getLkm()); 
    kayttajat.lisaa(aada); assertEquals("From: Kayttajat line: 45", 3, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 46", aada, kayttajat.anna(0)); 
    assertEquals("From: Kayttajat line: 47", ben, kayttajat.anna(1)); 
    assertEquals("From: Kayttajat line: 48", aada, kayttajat.anna(2)); 
    assertEquals("From: Kayttajat line: 49", false, kayttajat.anna(1) == aada); 
    assertEquals("From: Kayttajat line: 50", true, kayttajat.anna(1) == ben); 
    try {
    assertEquals("From: Kayttajat line: 51", aada, kayttajat.anna(3)); 
    fail("Kayttajat: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kayttajat.lisaa(aada); assertEquals("From: Kayttajat line: 52", 4, kayttajat.getLkm()); 
    kayttajat.lisaa(aada); assertEquals("From: Kayttajat line: 53", 5, kayttajat.getLkm()); 
  } // Generated by ComTest END
}