package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.07 13:14:17 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KotitalousTest {



  // Generated by ComTest BEGIN
  /** testLisaa31 */
  @Test
  public void testLisaa31() {    // Kotitalous: 31
    Kotitalous kt = new Kotitalous(); 
    Kayttaja aada = new Kayttaja(), ben = new Kayttaja(); 
    aada.rekisteroi(); ben.rekisteroi(); 
    assertEquals("From: Kotitalous line: 35", 0, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 36", 1, kt.getKayttajia()); 
    kt.lisaa(ben); assertEquals("From: Kotitalous line: 37", 2, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 38", 3, kt.getKayttajia()); 
    assertEquals("From: Kotitalous line: 39", aada, kt.annaKayttaja(0)); 
    assertEquals("From: Kotitalous line: 40", ben, kt.annaKayttaja(1)); 
    assertEquals("From: Kotitalous line: 41", aada, kt.annaKayttaja(2)); 
    try {
    assertEquals("From: Kotitalous line: 42", aada, kt.annaKayttaja(3)); 
    fail("Kotitalous: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 43", 4, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 44", 5, kt.getKayttajia()); 
  } // Generated by ComTest END
}