package kotitalous.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.22 18:54:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KotitalousTest {



  // Generated by ComTest BEGIN
  /** testLisaa36 */
  @Test
  public void testLisaa36() {    // Kotitalous: 36
    Kotitalous kt = new Kotitalous(); 
    Kayttaja aada = new Kayttaja(), ben = new Kayttaja(); 
    aada.rekisteroi(); ben.rekisteroi(); 
    assertEquals("From: Kotitalous line: 40", 0, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 41", 1, kt.getKayttajia()); 
    kt.lisaa(ben); assertEquals("From: Kotitalous line: 42", 2, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 43", 3, kt.getKayttajia()); 
    assertEquals("From: Kotitalous line: 44", aada, kt.annaKayttaja(0)); 
    assertEquals("From: Kotitalous line: 45", ben, kt.annaKayttaja(1)); 
    assertEquals("From: Kotitalous line: 46", aada, kt.annaKayttaja(2)); 
    try {
    assertEquals("From: Kotitalous line: 47", aada, kt.annaKayttaja(3)); 
    fail("Kotitalous: 47 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 48", 4, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 49", 5, kt.getKayttajia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaSovitutKayttajat193 */
  @Test
  public void testAnnaSovitutKayttajat193() {    // Kotitalous: 193
    Kotitalous kt = new Kotitalous(); 
    Kayttaja aada = new Kayttaja(), ben = new Kayttaja(); 
    aada.rekisteroi(); ben.rekisteroi(); 
    Tehtava imu1 = new Tehtava(), imu2 = new Tehtava(), imu3 = new Tehtava(); 
    imu1.rekisteroi(); imu2.rekisteroi(); imu3.rekisteroi(); 
    SovittuTehtava st1 = new SovittuTehtava(), st2 = new SovittuTehtava(); 
    SovittuTehtava st3 = new SovittuTehtava(), st4 = new SovittuTehtava(); 
    st1.setKayttaja(aada); st1.setTehtava(imu1); 
    st2.setKayttaja(aada); st2.setTehtava(imu2); 
    st3.setKayttaja(aada); st3.setTehtava(imu3); 
    st4.setKayttaja(ben); st4.setTehtava(imu3); 
    kt.lisaa(aada); kt.lisaa(ben); 
    kt.lisaa(imu1); kt.lisaa(imu2); kt.lisaa(imu3); 
    kt.lisaa(st1); kt.lisaa(st2); kt.lisaa(st3); kt.lisaa(st4); 
    List<SovittuTehtava> loydetyt = kt.annaSovitutKayttajat(imu1); 
    assertEquals("From: Kotitalous line: 212", 1, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 213", st1, loydetyt.get(0)); 
    loydetyt = kt.annaSovitutKayttajat(imu2); 
    assertEquals("From: Kotitalous line: 215", 1, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 216", st2, loydetyt.get(0)); 
    loydetyt = kt.annaSovitutKayttajat(imu3); 
    assertEquals("From: Kotitalous line: 218", 2, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 219", st3, loydetyt.get(0)); 
    assertEquals("From: Kotitalous line: 220", st4, loydetyt.get(1)); 
    loydetyt = kt.annaSovitutTehtavat(aada); 
    assertEquals("From: Kotitalous line: 222", 3, loydetyt.size()); 
    loydetyt = kt.annaSovitutTehtavat(ben); 
    assertEquals("From: Kotitalous line: 224", 1, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 225", st4, loydetyt.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta252 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta252() throws SailoException {    // Kotitalous: 252
    Kotitalous kt = new Kotitalous(); 
    Kayttaja aada1 = new Kayttaja(); aada1.rekisteroi(); aada1.taytaAadaTiedoilla(); 
    Kayttaja aada2 = new Kayttaja(); aada2.rekisteroi(); aada2.taytaAadaTiedoilla(); 
    Kayttaja aada3 = new Kayttaja(); aada3.rekisteroi(); aada3.taytaAadaTiedoilla(); 
    Tehtava imu12 = new Tehtava(); imu12.rekisteroi(); imu12.taytaImurointiTiedoilla(); 
    Tehtava imu23 = new Tehtava(); imu23.rekisteroi(); imu23.taytaImurointiTiedoilla(); 
    Tehtava imu34 = new Tehtava(); imu34.rekisteroi(); imu34.taytaImurointiTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); st.setKayttaja(aada1); st.setTehtava(imu12); 
    String tiedNimi = "testiKotitalous"; 
    File ftied = new File(tiedNimi + "/kayttajat.dat"); 
    File ftied2 = new File(tiedNimi + "/tehtavat.dat"); 
    File ftied3 = new File(tiedNimi + "/sovitut.dat"); 
    ftied.delete(); ftied2.delete(); ftied3.delete(); 
    try {
    kt.lueTiedostosta(tiedNimi); 
    fail("Kotitalous: 269 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kt.lisaa(aada1); kt.lisaa(aada2); kt.lisaa(aada3); 
    kt.lisaa(imu12); kt.lisaa(imu23); kt.lisaa(imu34); 
    kt.lisaa(st); 
    kt.tallenna(tiedNimi); 
    kt = new Kotitalous(); 
    kt.lueTiedostosta(tiedNimi); 
    assertEquals("From: Kotitalous line: 277", 3, kt.getKayttajia()); 
    assertEquals("From: Kotitalous line: 278", aada1.toString(), kt.annaKayttaja(0).toString()); 
    kt.poista(aada1); 
    assertEquals("From: Kotitalous line: 280", false, kt.annaKayttaja(0).toString() == aada1.toString()); 
    assertEquals("From: Kotitalous line: 281", aada2.toString(), kt.annaKayttaja(0).toString()); 
    assertEquals("From: Kotitalous line: 282", 2, kt.getKayttajia()); 
    assertEquals("From: Kotitalous line: 283", imu12.toString(), kt.etsiTehtava(imu12.getTid()).toString()); 
    kt.tallenna(tiedNimi); 
    assertEquals("From: Kotitalous line: 286", true, ftied.delete()); 
    assertEquals("From: Kotitalous line: 287", true, ftied2.delete()); 
    assertEquals("From: Kotitalous line: 288", true, ftied3.delete()); 
  } // Generated by ComTest END
}