package kotitalous.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.16 10:42:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KotitalousTest {



  // Generated by ComTest BEGIN
  /** testLisaa35 */
  @Test
  public void testLisaa35() {    // Kotitalous: 35
    Kotitalous kt = new Kotitalous(); 
    Kayttaja aada = new Kayttaja(), ben = new Kayttaja(); 
    aada.rekisteroi(); ben.rekisteroi(); 
    assertEquals("From: Kotitalous line: 39", 0, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 40", 1, kt.getKayttajia()); 
    kt.lisaa(ben); assertEquals("From: Kotitalous line: 41", 2, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 42", 3, kt.getKayttajia()); 
    assertEquals("From: Kotitalous line: 43", aada, kt.annaKayttaja(0)); 
    assertEquals("From: Kotitalous line: 44", ben, kt.annaKayttaja(1)); 
    assertEquals("From: Kotitalous line: 45", aada, kt.annaKayttaja(2)); 
    try {
    assertEquals("From: Kotitalous line: 46", aada, kt.annaKayttaja(3)); 
    fail("Kotitalous: 46 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 47", 4, kt.getKayttajia()); 
    kt.lisaa(aada); assertEquals("From: Kotitalous line: 48", 5, kt.getKayttajia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaSovitutKayttajat127 */
  @Test
  public void testAnnaSovitutKayttajat127() {    // Kotitalous: 127
    Kotitalous kt = new Kotitalous(); 
    Kayttaja aada = new Kayttaja(), ben = new Kayttaja(); 
    aada.rekisteroi(); ben.rekisteroi(); 
    Tehtava imu1 = new Tehtava(), imu2 = new Tehtava(), imu3 = new Tehtava(); 
    imu1.rekisteroi(); imu2.rekisteroi(); imu3.rekisteroi(); 
    SovittuTehtava st1 = new SovittuTehtava(), st2 = new SovittuTehtava(); 
    SovittuTehtava st3 = new SovittuTehtava(), st4 = new SovittuTehtava(); 
    st1.setKayttaja(aada); st1.setTehtava(imu1); 
    st2.setKayttaja(aada); st2.setTehtava(imu2); 
    st3.setKayttaja(aada); st3.setTehtava(imu3); 
    st4.setKayttaja(ben); st4.setTehtava(imu3); 
    kt.lisaa(aada); kt.lisaa(ben); 
    kt.lisaa(imu1); kt.lisaa(imu2); kt.lisaa(imu3); 
    kt.lisaa(st1); kt.lisaa(st2); kt.lisaa(st3); kt.lisaa(st4); 
    List<SovittuTehtava> loydetyt = kt.annaSovitutKayttajat(imu1); 
    assertEquals("From: Kotitalous line: 146", 1, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 147", st1, loydetyt.get(0)); 
    loydetyt = kt.annaSovitutKayttajat(imu2); 
    assertEquals("From: Kotitalous line: 149", 1, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 150", st2, loydetyt.get(0)); 
    loydetyt = kt.annaSovitutKayttajat(imu3); 
    assertEquals("From: Kotitalous line: 152", 2, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 153", st3, loydetyt.get(0)); 
    assertEquals("From: Kotitalous line: 154", st4, loydetyt.get(1)); 
    loydetyt = kt.annaSovitutTehtavat(aada); 
    assertEquals("From: Kotitalous line: 156", 3, loydetyt.size()); 
    loydetyt = kt.annaSovitutTehtavat(ben); 
    assertEquals("From: Kotitalous line: 158", 1, loydetyt.size()); 
    assertEquals("From: Kotitalous line: 159", st4, loydetyt.get(0)); 
  } // Generated by ComTest END
}