package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.16 09:34:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SovittuTehtavaTest {


  // Generated by ComTest BEGIN
  /** testSetKayttaja24 */
  @Test
  public void testSetKayttaja24() {    // SovittuTehtava: 24
    Kayttaja aada = new Kayttaja(); 
    aada.rekisteroi(); 
    aada.taytaAadaTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); 
    st.setKayttaja(aada); 
    assertEquals("From: SovittuTehtava line: 30", aada.getKid(), st.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetTehtava42 */
  @Test
  public void testSetTehtava42() {    // SovittuTehtava: 42
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    t1.taytaImurointiTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); 
    st.setTehtava(t1); 
    assertEquals("From: SovittuTehtava line: 48", t1.getTid(), st.getTid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKid59 */
  @Test
  public void testGetKid59() {    // SovittuTehtava: 59
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 61", 0, st.getKid()); 
    Kayttaja aada = new Kayttaja(); 
    aada.rekisteroi(); 
    st.setKayttaja(aada); 
    assertEquals("From: SovittuTehtava line: 65", aada.getKid(), st.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTid76 */
  @Test
  public void testGetTid76() {    // SovittuTehtava: 76
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 78", 0, st.getTid()); 
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    st.setTehtava(t1); 
    assertEquals("From: SovittuTehtava line: 82", t1.getTid(), st.getTid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString102 */
  @Test
  public void testToString102() {    // SovittuTehtava: 102
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 104", "0|0", st.toString()); 
  } // Generated by ComTest END
}