package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.23 13:59:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SovittuTehtavaTest {



  // Generated by ComTest BEGIN
  /** testSetKayttaja29 */
  @Test
  public void testSetKayttaja29() {    // SovittuTehtava: 29
    Kayttaja aada = new Kayttaja(); 
    aada.rekisteroi(); 
    aada.taytaAadaTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); 
    st.setKayttaja(aada); 
    assertEquals("From: SovittuTehtava line: 35", aada.getKid(), st.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetTehtava48 */
  @Test
  public void testSetTehtava48() {    // SovittuTehtava: 48
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    t1.taytaImurointiTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); 
    st.setTehtava(t1); 
    assertEquals("From: SovittuTehtava line: 54", t1.getTid(), st.getTid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKid66 */
  @Test
  public void testGetKid66() {    // SovittuTehtava: 66
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 68", 0, st.getKid()); 
    Kayttaja aada = new Kayttaja(); 
    aada.rekisteroi(); 
    st.setKayttaja(aada); 
    assertEquals("From: SovittuTehtava line: 72", aada.getKid(), st.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTid84 */
  @Test
  public void testGetTid84() {    // SovittuTehtava: 84
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 86", 0, st.getTid()); 
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    st.setTehtava(t1); 
    assertEquals("From: SovittuTehtava line: 90", t1.getTid(), st.getTid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString111 */
  @Test
  public void testToString111() {    // SovittuTehtava: 111
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 113", "0|0", st.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse126 */
  @Test
  public void testParse126() {    // SovittuTehtava: 126
    SovittuTehtava st = new SovittuTehtava(); 
    st.parse("  1   |   2"); 
    assertEquals("From: SovittuTehtava line: 129", 1, st.getKid()); 
    assertEquals("From: SovittuTehtava line: 130", 2, st.getTid()); 
    assertEquals("From: SovittuTehtava line: 131", "1|2", st.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals146 */
  @Test
  public void testEquals146() {    // SovittuTehtava: 146
    SovittuTehtava st1 = new SovittuTehtava(); 
    SovittuTehtava st2 = new SovittuTehtava(); 
    SovittuTehtava st3 = new SovittuTehtava(); 
    st1.parse("1 | 1"); 
    st2.parse("   2 | 1"); 
    st3.parse("   1|1   "); 
    assertEquals("From: SovittuTehtava line: 154", false, st1.equals(st2)); 
    assertEquals("From: SovittuTehtava line: 155", false, st2.equals(st1)); 
    assertEquals("From: SovittuTehtava line: 156", false, st2.equals(st3)); 
    assertEquals("From: SovittuTehtava line: 157", true, st1.equals(st3)); 
    assertEquals("From: SovittuTehtava line: 158", true, st3.equals(st1)); 
  } // Generated by ComTest END
}