package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.22 16:34:24 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class SovittuTehtavaTest {



  // Generated by ComTest BEGIN
  /** testSetKayttaja26 */
  @Test
  public void testSetKayttaja26() {    // SovittuTehtava: 26
    Kayttaja aada = new Kayttaja(); 
    aada.rekisteroi(); 
    aada.taytaAadaTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); 
    st.setKayttaja(aada); 
    assertEquals("From: SovittuTehtava line: 32", aada.getKid(), st.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetTehtava44 */
  @Test
  public void testSetTehtava44() {    // SovittuTehtava: 44
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    t1.taytaImurointiTiedoilla(); 
    SovittuTehtava st = new SovittuTehtava(); 
    st.setTehtava(t1); 
    assertEquals("From: SovittuTehtava line: 50", t1.getTid(), st.getTid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKid61 */
  @Test
  public void testGetKid61() {    // SovittuTehtava: 61
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 63", 0, st.getKid()); 
    Kayttaja aada = new Kayttaja(); 
    aada.rekisteroi(); 
    st.setKayttaja(aada); 
    assertEquals("From: SovittuTehtava line: 67", aada.getKid(), st.getKid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTid78 */
  @Test
  public void testGetTid78() {    // SovittuTehtava: 78
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 80", 0, st.getTid()); 
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    st.setTehtava(t1); 
    assertEquals("From: SovittuTehtava line: 84", t1.getTid(), st.getTid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString104 */
  @Test
  public void testToString104() {    // SovittuTehtava: 104
    SovittuTehtava st = new SovittuTehtava(); 
    assertEquals("From: SovittuTehtava line: 106", "0|0", st.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse119 */
  @Test
  public void testParse119() {    // SovittuTehtava: 119
    SovittuTehtava st = new SovittuTehtava(); 
    st.parse("  1   |   2"); 
    assertEquals("From: SovittuTehtava line: 122", 1, st.getKid()); 
    assertEquals("From: SovittuTehtava line: 123", 2, st.getTid()); 
    assertEquals("From: SovittuTehtava line: 124", "1|2", st.toString()); 
  } // Generated by ComTest END
}