package kotitalous.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.21 13:33:14 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TehtavatTest {



  // Generated by ComTest BEGIN
  /** testKorvaaTaiLisaa43 */
  @Test
  public void testKorvaaTaiLisaa43() {    // Tehtavat: 43
    Tehtavat tehtavat = new Tehtavat(); 
    Tehtava t = new Tehtava(), t2 = new Tehtava(); 
    t.rekisteroi(); t2.rekisteroi(); 
    assertEquals("From: Tehtavat line: 47", 0, tehtavat.getLkm()); 
    tehtavat.korvaaTaiLisaa(t); assertEquals("From: Tehtavat line: 48", 1, tehtavat.getLkm()); 
    tehtavat.korvaaTaiLisaa(t2); assertEquals("From: Tehtavat line: 49", 2, tehtavat.getLkm()); 
    Tehtava t3 = new Tehtava(); 
    try {
    t3 = t.clone(); 
    } catch (CloneNotSupportedException e) {
    System.out.println(e.getMessage()); 
    }
    t3.aseta(1, "Imurointi"); 
    Iterator<Tehtava> it = tehtavat.iterator(); 
    assertEquals("From: Tehtavat line: 58", true, it.next() == t); 
    tehtavat.korvaaTaiLisaa(t3); assertEquals("From: Tehtavat line: 59", 2, tehtavat.getLkm()); 
    it = tehtavat.iterator(); 
    Tehtava t0 = it.next(); 
    assertEquals("From: Tehtavat line: 62", t3, t0); 
    assertEquals("From: Tehtavat line: 63", false, t0 == t); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi86 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi86() throws SailoException {    // Tehtavat: 86
    Tehtavat teet = new Tehtavat(); 
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    teet.lisaa(t1); 
    assertEquals("From: Tehtavat line: 92", t1, teet.etsi(t1.getTid())); 
    try {
    teet.etsi(200); 
    fail("Tehtavat: 93 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm107 */
  @Test
  public void testGetLkm107() {    // Tehtavat: 107
    Tehtavat teet = new Tehtavat(); 
    assertEquals("From: Tehtavat line: 109", 0, teet.getLkm()); 
    teet.lisaa(new Tehtava()); 
    assertEquals("From: Tehtavat line: 111", 1, teet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta138 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta138() throws SailoException {    // Tehtavat: 138
    Tehtavat teet = new Tehtavat(); 
    Tehtava imu12 = new Tehtava(); imu12.rekisteroi(); imu12.taytaImurointiTiedoilla(); 
    Tehtava imu23 = new Tehtava(); imu23.rekisteroi(); imu23.taytaImurointiTiedoilla(); 
    Tehtava imu34 = new Tehtava(); imu34.rekisteroi(); imu34.taytaImurointiTiedoilla(); 
    String tiedNimi = "testiKotitalous"; 
    File ftied = new File(tiedNimi + "/tehtavat.dat"); 
    ftied.delete(); 
    try {
    teet.lueTiedostosta(tiedNimi); 
    fail("Tehtavat: 149 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    teet.lisaa(imu12); 
    teet.lisaa(imu23); 
    teet.lisaa(imu34); 
    teet.tallenna(tiedNimi); 
    teet = new Tehtavat(); 
    teet.lueTiedostosta(tiedNimi); 
    Iterator<Tehtava> i = teet.iterator(); 
    assertEquals("From: Tehtavat line: 157", imu12.toString(), i.next().toString()); 
    assertEquals("From: Tehtavat line: 158", imu23.toString(), i.next().toString()); 
    assertEquals("From: Tehtavat line: 159", imu34.toString(), i.next().toString()); 
    assertEquals("From: Tehtavat line: 160", false, i.hasNext()); 
    teet.lisaa(imu12); 
    teet.tallenna(tiedNimi); 
    assertEquals("From: Tehtavat line: 163", true, ftied.delete()); 
  } // Generated by ComTest END
}