package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.15 14:17:51 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TehtavaTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi31 */
  @Test
  public void testRekisteroi31() {    // Tehtava: 31
    Tehtava t1 = new Tehtava(); 
    assertEquals("From: Tehtava line: 33", 0, t1.getTid()); 
    t1.rekisteroi(); 
    Tehtava t2 = new Tehtava(); 
    t2.rekisteroi(); 
    int n1 = t1.getTid(); 
    int n2 = t2.getTid(); 
    assertEquals("From: Tehtava line: 39", n2-1, n1); 
  } // Generated by ComTest END
}