package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.13 14:06:59 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TehtavaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi43 */
  @Test
  public void testRekisteroi43() {    // Tehtava: 43
    Tehtava t1 = new Tehtava(); 
    assertEquals("From: Tehtava line: 45", 0, t1.getTid()); 
    t1.rekisteroi(); 
    Tehtava t2 = new Tehtava(); 
    t2.rekisteroi(); 
    int n1 = t1.getTid(); 
    int n2 = t2.getTid(); 
    assertEquals("From: Tehtava line: 51", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna115 */
  @Test
  public void testAnna115() {    // Tehtava: 115
    Tehtava t = new Tehtava(); 
    t.parse("3 |   Imurointi   |  40   |   10   "); 
    assertEquals("From: Tehtava line: 118", "3", t.anna(0)); 
    assertEquals("From: Tehtava line: 119", "Imurointi", t.anna(1)); 
    assertEquals("From: Tehtava line: 120", "40", t.anna(2)); 
    assertEquals("From: Tehtava line: 121", "10", t.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta144 */
  @Test
  public void testAseta144() {    // Tehtava: 144
    Tehtava t = new Tehtava(); 
    assertEquals("From: Tehtava line: 146", "Nimi ei saa olla tyhjä", t.aseta(1, "")); 
    assertEquals("From: Tehtava line: 147", "Merkki | ei ole sallittu", t.aseta(1, "Imurointi |")); 
    assertEquals("From: Tehtava line: 148", "Anna kokonaisluku, minuutteja", t.aseta(2, "kissa")); 
    assertEquals("From: Tehtava line: 149", null, t.aseta(2, "30")); 
    assertEquals("From: Tehtava line: 150", "Suurin sallittu luku 18", t.aseta(3, "100")); 
    assertEquals("From: Tehtava line: 151", "Anna kokonaisluku", t.aseta(3, "-1")); 
    assertEquals("From: Tehtava line: 152", null, t.aseta(3, "3")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone188 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone188() throws CloneNotSupportedException {    // Tehtava: 188
    Tehtava t = new Tehtava(); 
    t.parse("3 |   Imurointi   |  40   |   10   "); 
    Tehtava kopio = t.clone(); 
    assertEquals("From: Tehtava line: 193", t.toString(), kopio.toString()); 
    t.parse("  4 |  Moppaus |  20 | 10   "); 
    assertEquals("From: Tehtava line: 195", false, kopio.toString().equals(t.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse224 */
  @Test
  public void testParse224() {    // Tehtava: 224
    Tehtava tehtava = new Tehtava(); 
    tehtava.parse("   2   |  Imurointi     | 30 |  10    "); 
    assertEquals("From: Tehtava line: 227", 2, tehtava.getTid()); 
    assertEquals("From: Tehtava line: 228", "2|Imurointi|30|10", tehtava.toString()); 
    tehtava.rekisteroi(); 
    int n = tehtava.getTid(); 
    tehtava.parse(""+(n+20)); 
    tehtava.rekisteroi(); 
    assertEquals("From: Tehtava line: 234", n+20+1, tehtava.getTid()); 
    assertEquals("From: Tehtava line: 235", "" + (n+20+1) + "|Imurointi|30|10", tehtava.toString()); 
  } // Generated by ComTest END
}