package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.11 11:30:29 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TehtavatTest {



  // Generated by ComTest BEGIN
  /** 
   * testEtsi33 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi33() throws SailoException {    // Tehtavat: 33
    Tehtavat teet = new Tehtavat(); 
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    teet.lisaa(t1); 
    assertEquals("From: Tehtavat line: 39", t1, teet.etsi(t1.getTid())); 
    try {
    teet.etsi(200); 
    fail("Tehtavat: 40 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm54 */
  @Test
  public void testGetLkm54() {    // Tehtavat: 54
    Tehtavat teet = new Tehtavat(); 
    assertEquals("From: Tehtavat line: 56", 0, teet.getLkm()); 
    teet.lisaa(new Tehtava()); 
    assertEquals("From: Tehtavat line: 58", 1, teet.getLkm()); 
  } // Generated by ComTest END
}