package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.22 10:08:49 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TehtavaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi42 */
  @Test
  public void testRekisteroi42() {    // Tehtava: 42
    Tehtava t1 = new Tehtava(); 
    assertEquals("From: Tehtava line: 44", 0, t1.getTid()); 
    t1.rekisteroi(); 
    Tehtava t2 = new Tehtava(); 
    t2.rekisteroi(); 
    int n1 = t1.getTid(); 
    int n2 = t2.getTid(); 
    assertEquals("From: Tehtava line: 50", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse94 */
  @Test
  public void testParse94() {    // Tehtava: 94
    Tehtava tehtava = new Tehtava(); 
    tehtava.parse("   2   |  Imurointi     | 10 |  30    "); 
    assertEquals("From: Tehtava line: 97", 2, tehtava.getTid()); 
    assertEquals("From: Tehtava line: 98", "2|Imurointi|10|30", tehtava.toString()); 
    tehtava.rekisteroi(); 
    int n = tehtava.getTid(); 
    tehtava.parse(""+(n+20)); 
    tehtava.rekisteroi(); 
    assertEquals("From: Tehtava line: 104", n+20+1, tehtava.getTid()); 
    assertEquals("From: Tehtava line: 105", "" + (n+20+1) + "|Imurointi|10|30", tehtava.toString()); 
  } // Generated by ComTest END
}