package kotitalous.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kotitalous.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.06 15:28:57 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TehtavatTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnna32 
   * @throws SailoException when error
   */
  @Test
  public void testAnna32() throws SailoException {    // Tehtavat: 32
    Tehtavat teet = new Tehtavat(); 
    Tehtava t1 = new Tehtava(); 
    t1.rekisteroi(); 
    teet.lisaa(t1); 
    assertEquals("From: Tehtavat line: 38", t1, teet.anna(t1.getTid())); 
    try {
    teet.anna(200); 
    fail("Tehtavat: 39 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm53 */
  @Test
  public void testGetLkm53() {    // Tehtavat: 53
    Tehtavat teet = new Tehtavat(); 
    assertEquals("From: Tehtavat line: 55", 0, teet.getLkm()); 
    teet.lisaa(new Tehtava()); 
    assertEquals("From: Tehtavat line: 57", 1, teet.getLkm()); 
  } // Generated by ComTest END
}